name: Starter
main: Starter.MyPlugin

description: Starter Minigame Template for the Skillquest Hackathon
author: Ben Nylund

version: 1.0
api-version: 1.16
softdepend: [SidebarAPI, Multiverse-Core, MinigamesAPI]
